[package]
name = "moisture-meter"
version = "0.1.0"
authors = ["Aleksander Kleinszmidt <60325364+Xarwex@users.noreply.github.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"

[[bin]]
name = "moisture-meter"
path = "src/main.rs"
test = false
doctest = false
bench = false

[dependencies]
embassy-executor = "0.9.0"
embassy-net = { version = "0.8.0", features = ["dhcpv4", "dns", "medium-ethernet", "tcp"] }
embassy-time = "0.5.0"
esp-alloc = { version = "0.9.0", features = ["esp32"] }
esp-hal = { version = "1.0.0", features = ["esp32", "unstable"] }
esp-backtrace = { version = "0.18.1", features = [
  "esp32",
  "panic-handler",
  "println",
] }
esp-bootloader-esp-idf = { version = "0.4.0", features = ["esp32"] }
esp-println = { version = "0.16.1", features = ["esp32"] }
esp-radio = { version = "0.17.0", default-features = false, features = [
  "esp-alloc",
  "esp32",
  "wifi",
] }
esp-rtos = { version = "0.2.0", features = ["embassy", "esp-alloc", "esp-radio", "esp32"] }
heapless = "0.8.0"
nb = "1.1.0"
reqwless = { version = "0.14.0", default-features = false }
static_cell = "2.1.0"

# [features]
# default = ["esp-hal/xtal-40mhz"]
