[package]
name = "moisture-meter"
version = "0.1.0"
authors = ["Aleksander Kleinszmidt <60325364+Xarwex@users.noreply.github.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
esp-hal = { version = "1.0.0", features = ["esp32", "unstable"] }
esp-backtrace = { version = "0.18.1", features = [
  "esp32",
  "panic-handler",
  "println",
] }
esp-println = { version = "0.16.1", features = ["esp32"] }

# [features]
# default = ["esp-hal/xtal-40mhz"]
